[package]
name = "crypto-pair-ffi"
version = "0.0.1"
authors = ["soulmachine <soulmachine@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
crypto-pair = "2.0.5"

[build-dependencies]
cbindgen = "0.16.0"

[profile.release]
lto = true
codegen-units = 1
