/* Licensed under Apache-2.0 */

#ifndef CRYPTO_PAIR_H_
#define CRYPTO_PAIR_H_

/* Generated with cbindgen:0.16.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Normalize a cryptocurrency trading pair.
 */
const char *normalize_pair(const char *symbol, const char *exchange);

#endif /* CRYPTO_PAIR_H_ */
